namespace E94106119_practice_6_2
{
    partial class Form1
    {
        /// <summary>
        /// 設計工具所需的變數。
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// 清除任何使用中的資源。
        /// </summary>
        /// <param name="disposing">如果應該處置受控資源則為 true，否則為 false。</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form 設計工具產生的程式碼

        /// <summary>
        /// 此為設計工具支援所需的方法 - 請勿使用程式碼編輯器修改
        /// 這個方法的內容。
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.button1 = new System.Windows.Forms.Button();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.button2 = new System.Windows.Forms.Button();
            this.domainUpDown1 = new System.Windows.Forms.DomainUpDown();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.button3 = new System.Windows.Forms.Button();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.timer1 = new System.Windows.Forms.Timer(this.components);
            this.SuspendLayout();
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.Color.White;
            this.button1.FlatAppearance.BorderColor = System.Drawing.Color.White;
            this.button1.FlatAppearance.BorderSize = 0;
            this.button1.Location = new System.Drawing.Point(50, 195);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(75, 23);
            this.button1.TabIndex = 0;
            this.button1.Text = "選擇鬧鈴";
            this.button1.UseVisualStyleBackColor = false;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(131, 200);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(77, 12);
            this.label1.TabIndex = 1;
            this.label1.Text = "尚未選擇檔案";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(593, 197);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(77, 12);
            this.label2.TabIndex = 2;
            this.label2.Text = "設定鬧鐘時間";
            // 
            // button2
            // 
            this.button2.BackColor = System.Drawing.Color.White;
            this.button2.FlatAppearance.BorderColor = System.Drawing.Color.White;
            this.button2.Location = new System.Drawing.Point(790, 192);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(75, 23);
            this.button2.TabIndex = 3;
            this.button2.Text = "啟動";
            this.button2.UseVisualStyleBackColor = false;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // domainUpDown1
            // 
            this.domainUpDown1.AutoSize = true;
            this.domainUpDown1.Items.Add("上午 00:00");
            this.domainUpDown1.Items.Add("上午 00:01");
            this.domainUpDown1.Items.Add("上午 00:02");
            this.domainUpDown1.Items.Add("上午 00:03");
            this.domainUpDown1.Items.Add("上午 00:04");
            this.domainUpDown1.Items.Add("上午 00:05");
            this.domainUpDown1.Items.Add("上午 00:06");
            this.domainUpDown1.Items.Add("上午 00:07");
            this.domainUpDown1.Items.Add("上午 00:08");
            this.domainUpDown1.Items.Add("上午 00:09");
            this.domainUpDown1.Items.Add("上午 00:10");
            this.domainUpDown1.Items.Add("上午 00:11");
            this.domainUpDown1.Items.Add("上午 00:12");
            this.domainUpDown1.Items.Add("上午 00:13");
            this.domainUpDown1.Items.Add("上午 00:14");
            this.domainUpDown1.Items.Add("上午 00:15");
            this.domainUpDown1.Items.Add("上午 00:16");
            this.domainUpDown1.Items.Add("上午 00:17");
            this.domainUpDown1.Items.Add("上午 00:18");
            this.domainUpDown1.Items.Add("上午 00:19");
            this.domainUpDown1.Items.Add("上午 00:20");
            this.domainUpDown1.Items.Add("上午 00:21");
            this.domainUpDown1.Items.Add("上午 00:22");
            this.domainUpDown1.Items.Add("上午 00:23");
            this.domainUpDown1.Items.Add("上午 00:24");
            this.domainUpDown1.Items.Add("上午 00:25");
            this.domainUpDown1.Items.Add("上午 00:26");
            this.domainUpDown1.Items.Add("上午 00:27");
            this.domainUpDown1.Items.Add("上午 00:28");
            this.domainUpDown1.Items.Add("上午 00:29");
            this.domainUpDown1.Items.Add("上午 00:30");
            this.domainUpDown1.Items.Add("上午 00:31");
            this.domainUpDown1.Items.Add("上午 00:32");
            this.domainUpDown1.Items.Add("上午 00:33");
            this.domainUpDown1.Items.Add("上午 00:34");
            this.domainUpDown1.Items.Add("上午 00:35");
            this.domainUpDown1.Items.Add("上午 00:36");
            this.domainUpDown1.Items.Add("上午 00:37");
            this.domainUpDown1.Items.Add("上午 00:38");
            this.domainUpDown1.Items.Add("上午 00:39");
            this.domainUpDown1.Items.Add("上午 00:40");
            this.domainUpDown1.Items.Add("上午 00:41");
            this.domainUpDown1.Items.Add("上午 00:42");
            this.domainUpDown1.Items.Add("上午 00:43");
            this.domainUpDown1.Items.Add("上午 00:44");
            this.domainUpDown1.Items.Add("上午 00:45");
            this.domainUpDown1.Items.Add("上午 00:46");
            this.domainUpDown1.Items.Add("上午 00:47");
            this.domainUpDown1.Items.Add("上午 00:48");
            this.domainUpDown1.Items.Add("上午 00:49");
            this.domainUpDown1.Items.Add("上午 00:50");
            this.domainUpDown1.Items.Add("上午 00:51");
            this.domainUpDown1.Items.Add("上午 00:52");
            this.domainUpDown1.Items.Add("上午 00:53");
            this.domainUpDown1.Items.Add("上午 00:54");
            this.domainUpDown1.Items.Add("上午 00:55");
            this.domainUpDown1.Items.Add("上午 00:56");
            this.domainUpDown1.Items.Add("上午 00:57");
            this.domainUpDown1.Items.Add("上午 00:58");
            this.domainUpDown1.Items.Add("上午 00:59");
            this.domainUpDown1.Items.Add("上午 01:00");
            this.domainUpDown1.Items.Add("上午 01:01");
            this.domainUpDown1.Items.Add("上午 01:02");
            this.domainUpDown1.Items.Add("上午 01:03");
            this.domainUpDown1.Items.Add("上午 01:04");
            this.domainUpDown1.Items.Add("上午 01:05");
            this.domainUpDown1.Items.Add("上午 01:06");
            this.domainUpDown1.Items.Add("上午 01:07");
            this.domainUpDown1.Items.Add("上午 01:08");
            this.domainUpDown1.Items.Add("上午 01:09");
            this.domainUpDown1.Items.Add("上午 01:10");
            this.domainUpDown1.Items.Add("上午 01:11");
            this.domainUpDown1.Items.Add("上午 01:12");
            this.domainUpDown1.Items.Add("上午 01:13");
            this.domainUpDown1.Items.Add("上午 01:14");
            this.domainUpDown1.Items.Add("上午 01:15");
            this.domainUpDown1.Items.Add("上午 01:16");
            this.domainUpDown1.Items.Add("上午 01:17");
            this.domainUpDown1.Items.Add("上午 01:18");
            this.domainUpDown1.Items.Add("上午 01:19");
            this.domainUpDown1.Items.Add("上午 01:20");
            this.domainUpDown1.Items.Add("上午 01:21");
            this.domainUpDown1.Items.Add("上午 01:22");
            this.domainUpDown1.Items.Add("上午 01:23");
            this.domainUpDown1.Items.Add("上午 01:24");
            this.domainUpDown1.Items.Add("上午 01:25");
            this.domainUpDown1.Items.Add("上午 01:26");
            this.domainUpDown1.Items.Add("上午 01:27");
            this.domainUpDown1.Items.Add("上午 01:28");
            this.domainUpDown1.Items.Add("上午 01:29");
            this.domainUpDown1.Items.Add("上午 01:30");
            this.domainUpDown1.Items.Add("上午 01:31");
            this.domainUpDown1.Items.Add("上午 01:32");
            this.domainUpDown1.Items.Add("上午 01:33");
            this.domainUpDown1.Items.Add("上午 01:34");
            this.domainUpDown1.Items.Add("上午 01:35");
            this.domainUpDown1.Items.Add("上午 01:36");
            this.domainUpDown1.Items.Add("上午 01:37");
            this.domainUpDown1.Items.Add("上午 01:38");
            this.domainUpDown1.Items.Add("上午 01:39");
            this.domainUpDown1.Items.Add("上午 01:40");
            this.domainUpDown1.Items.Add("上午 01:41");
            this.domainUpDown1.Items.Add("上午 01:42");
            this.domainUpDown1.Items.Add("上午 01:43");
            this.domainUpDown1.Items.Add("上午 01:44");
            this.domainUpDown1.Items.Add("上午 01:45");
            this.domainUpDown1.Items.Add("上午 01:46");
            this.domainUpDown1.Items.Add("上午 01:47");
            this.domainUpDown1.Items.Add("上午 01:48");
            this.domainUpDown1.Items.Add("上午 01:49");
            this.domainUpDown1.Items.Add("上午 01:50");
            this.domainUpDown1.Items.Add("上午 01:51");
            this.domainUpDown1.Items.Add("上午 01:52");
            this.domainUpDown1.Items.Add("上午 01:53");
            this.domainUpDown1.Items.Add("上午 01:54");
            this.domainUpDown1.Items.Add("上午 01:55");
            this.domainUpDown1.Items.Add("上午 01:56");
            this.domainUpDown1.Items.Add("上午 01:57");
            this.domainUpDown1.Items.Add("上午 01:58");
            this.domainUpDown1.Items.Add("上午 01:59");
            this.domainUpDown1.Items.Add("上午 02:00");
            this.domainUpDown1.Items.Add("上午 02:01");
            this.domainUpDown1.Items.Add("上午 02:02");
            this.domainUpDown1.Items.Add("上午 02:03");
            this.domainUpDown1.Items.Add("上午 02:04");
            this.domainUpDown1.Items.Add("上午 02:05");
            this.domainUpDown1.Items.Add("上午 02:06");
            this.domainUpDown1.Items.Add("上午 02:07");
            this.domainUpDown1.Items.Add("上午 02:08");
            this.domainUpDown1.Items.Add("上午 02:09");
            this.domainUpDown1.Items.Add("上午 02:10");
            this.domainUpDown1.Items.Add("上午 02:11");
            this.domainUpDown1.Items.Add("上午 02:12");
            this.domainUpDown1.Items.Add("上午 02:13");
            this.domainUpDown1.Items.Add("上午 02:14");
            this.domainUpDown1.Items.Add("上午 02:15");
            this.domainUpDown1.Items.Add("上午 02:16");
            this.domainUpDown1.Items.Add("上午 02:17");
            this.domainUpDown1.Items.Add("上午 02:18");
            this.domainUpDown1.Items.Add("上午 02:19");
            this.domainUpDown1.Items.Add("上午 02:20");
            this.domainUpDown1.Items.Add("上午 02:21");
            this.domainUpDown1.Items.Add("上午 02:22");
            this.domainUpDown1.Items.Add("上午 02:23");
            this.domainUpDown1.Items.Add("上午 02:24");
            this.domainUpDown1.Items.Add("上午 02:25");
            this.domainUpDown1.Items.Add("上午 02:26");
            this.domainUpDown1.Items.Add("上午 02:27");
            this.domainUpDown1.Items.Add("上午 02:28");
            this.domainUpDown1.Items.Add("上午 02:29");
            this.domainUpDown1.Items.Add("上午 02:30");
            this.domainUpDown1.Items.Add("上午 02:31");
            this.domainUpDown1.Items.Add("上午 02:32");
            this.domainUpDown1.Items.Add("上午 02:33");
            this.domainUpDown1.Items.Add("上午 02:34");
            this.domainUpDown1.Items.Add("上午 02:35");
            this.domainUpDown1.Items.Add("上午 02:36");
            this.domainUpDown1.Items.Add("上午 02:37");
            this.domainUpDown1.Items.Add("上午 02:38");
            this.domainUpDown1.Items.Add("上午 02:39");
            this.domainUpDown1.Items.Add("上午 02:40");
            this.domainUpDown1.Items.Add("上午 02:41");
            this.domainUpDown1.Items.Add("上午 02:42");
            this.domainUpDown1.Items.Add("上午 02:43");
            this.domainUpDown1.Items.Add("上午 02:44");
            this.domainUpDown1.Items.Add("上午 02:45");
            this.domainUpDown1.Items.Add("上午 02:46");
            this.domainUpDown1.Items.Add("上午 02:47");
            this.domainUpDown1.Items.Add("上午 02:48");
            this.domainUpDown1.Items.Add("上午 02:49");
            this.domainUpDown1.Items.Add("上午 02:50");
            this.domainUpDown1.Items.Add("上午 02:51");
            this.domainUpDown1.Items.Add("上午 02:52");
            this.domainUpDown1.Items.Add("上午 02:53");
            this.domainUpDown1.Items.Add("上午 02:54");
            this.domainUpDown1.Items.Add("上午 02:55");
            this.domainUpDown1.Items.Add("上午 02:56");
            this.domainUpDown1.Items.Add("上午 02:57");
            this.domainUpDown1.Items.Add("上午 02:58");
            this.domainUpDown1.Items.Add("上午 02:59");
            this.domainUpDown1.Items.Add("上午 03:00");
            this.domainUpDown1.Items.Add("上午 03:01");
            this.domainUpDown1.Items.Add("上午 03:02");
            this.domainUpDown1.Items.Add("上午 03:03");
            this.domainUpDown1.Items.Add("上午 03:04");
            this.domainUpDown1.Items.Add("上午 03:05");
            this.domainUpDown1.Items.Add("上午 03:06");
            this.domainUpDown1.Items.Add("上午 03:07");
            this.domainUpDown1.Items.Add("上午 03:08");
            this.domainUpDown1.Items.Add("上午 03:09");
            this.domainUpDown1.Items.Add("上午 03:10");
            this.domainUpDown1.Items.Add("上午 03:11");
            this.domainUpDown1.Items.Add("上午 03:12");
            this.domainUpDown1.Items.Add("上午 03:13");
            this.domainUpDown1.Items.Add("上午 03:14");
            this.domainUpDown1.Items.Add("上午 03:15");
            this.domainUpDown1.Items.Add("上午 03:16");
            this.domainUpDown1.Items.Add("上午 03:17");
            this.domainUpDown1.Items.Add("上午 03:18");
            this.domainUpDown1.Items.Add("上午 03:19");
            this.domainUpDown1.Items.Add("上午 03:20");
            this.domainUpDown1.Items.Add("上午 03:21");
            this.domainUpDown1.Items.Add("上午 03:22");
            this.domainUpDown1.Items.Add("上午 03:23");
            this.domainUpDown1.Items.Add("上午 03:24");
            this.domainUpDown1.Items.Add("上午 03:25");
            this.domainUpDown1.Items.Add("上午 03:26");
            this.domainUpDown1.Items.Add("上午 03:27");
            this.domainUpDown1.Items.Add("上午 03:28");
            this.domainUpDown1.Items.Add("上午 03:29");
            this.domainUpDown1.Items.Add("上午 03:30");
            this.domainUpDown1.Items.Add("上午 03:31");
            this.domainUpDown1.Items.Add("上午 03:32");
            this.domainUpDown1.Items.Add("上午 03:33");
            this.domainUpDown1.Items.Add("上午 03:34");
            this.domainUpDown1.Items.Add("上午 03:35");
            this.domainUpDown1.Items.Add("上午 03:36");
            this.domainUpDown1.Items.Add("上午 03:37");
            this.domainUpDown1.Items.Add("上午 03:38");
            this.domainUpDown1.Items.Add("上午 03:39");
            this.domainUpDown1.Items.Add("上午 03:40");
            this.domainUpDown1.Items.Add("上午 03:41");
            this.domainUpDown1.Items.Add("上午 03:42");
            this.domainUpDown1.Items.Add("上午 03:43");
            this.domainUpDown1.Items.Add("上午 03:44");
            this.domainUpDown1.Items.Add("上午 03:45");
            this.domainUpDown1.Items.Add("上午 03:46");
            this.domainUpDown1.Items.Add("上午 03:47");
            this.domainUpDown1.Items.Add("上午 03:48");
            this.domainUpDown1.Items.Add("上午 03:49");
            this.domainUpDown1.Items.Add("上午 03:50");
            this.domainUpDown1.Items.Add("上午 03:51");
            this.domainUpDown1.Items.Add("上午 03:52");
            this.domainUpDown1.Items.Add("上午 03:53");
            this.domainUpDown1.Items.Add("上午 03:54");
            this.domainUpDown1.Items.Add("上午 03:55");
            this.domainUpDown1.Items.Add("上午 03:56");
            this.domainUpDown1.Items.Add("上午 03:57");
            this.domainUpDown1.Items.Add("上午 03:58");
            this.domainUpDown1.Items.Add("上午 03:59");
            this.domainUpDown1.Items.Add("上午 04:00");
            this.domainUpDown1.Items.Add("上午 04:01");
            this.domainUpDown1.Items.Add("上午 04:02");
            this.domainUpDown1.Items.Add("上午 04:03");
            this.domainUpDown1.Items.Add("上午 04:04");
            this.domainUpDown1.Items.Add("上午 04:05");
            this.domainUpDown1.Items.Add("上午 04:06");
            this.domainUpDown1.Items.Add("上午 04:07");
            this.domainUpDown1.Items.Add("上午 04:08");
            this.domainUpDown1.Items.Add("上午 04:09");
            this.domainUpDown1.Items.Add("上午 04:10");
            this.domainUpDown1.Items.Add("上午 04:11");
            this.domainUpDown1.Items.Add("上午 04:12");
            this.domainUpDown1.Items.Add("上午 04:13");
            this.domainUpDown1.Items.Add("上午 04:14");
            this.domainUpDown1.Items.Add("上午 04:15");
            this.domainUpDown1.Items.Add("上午 04:16");
            this.domainUpDown1.Items.Add("上午 04:17");
            this.domainUpDown1.Items.Add("上午 04:18");
            this.domainUpDown1.Items.Add("上午 04:19");
            this.domainUpDown1.Items.Add("上午 04:20");
            this.domainUpDown1.Items.Add("上午 04:21");
            this.domainUpDown1.Items.Add("上午 04:22");
            this.domainUpDown1.Items.Add("上午 04:23");
            this.domainUpDown1.Items.Add("上午 04:24");
            this.domainUpDown1.Items.Add("上午 04:25");
            this.domainUpDown1.Items.Add("上午 04:26");
            this.domainUpDown1.Items.Add("上午 04:27");
            this.domainUpDown1.Items.Add("上午 04:28");
            this.domainUpDown1.Items.Add("上午 04:29");
            this.domainUpDown1.Items.Add("上午 04:30");
            this.domainUpDown1.Items.Add("上午 04:31");
            this.domainUpDown1.Items.Add("上午 04:32");
            this.domainUpDown1.Items.Add("上午 04:33");
            this.domainUpDown1.Items.Add("上午 04:34");
            this.domainUpDown1.Items.Add("上午 04:35");
            this.domainUpDown1.Items.Add("上午 04:36");
            this.domainUpDown1.Items.Add("上午 04:37");
            this.domainUpDown1.Items.Add("上午 04:38");
            this.domainUpDown1.Items.Add("上午 04:39");
            this.domainUpDown1.Items.Add("上午 04:40");
            this.domainUpDown1.Items.Add("上午 04:41");
            this.domainUpDown1.Items.Add("上午 04:42");
            this.domainUpDown1.Items.Add("上午 04:43");
            this.domainUpDown1.Items.Add("上午 04:44");
            this.domainUpDown1.Items.Add("上午 04:45");
            this.domainUpDown1.Items.Add("上午 04:46");
            this.domainUpDown1.Items.Add("上午 04:47");
            this.domainUpDown1.Items.Add("上午 04:48");
            this.domainUpDown1.Items.Add("上午 04:49");
            this.domainUpDown1.Items.Add("上午 04:50");
            this.domainUpDown1.Items.Add("上午 04:51");
            this.domainUpDown1.Items.Add("上午 04:52");
            this.domainUpDown1.Items.Add("上午 04:53");
            this.domainUpDown1.Items.Add("上午 04:54");
            this.domainUpDown1.Items.Add("上午 04:55");
            this.domainUpDown1.Items.Add("上午 04:56");
            this.domainUpDown1.Items.Add("上午 04:57");
            this.domainUpDown1.Items.Add("上午 04:58");
            this.domainUpDown1.Items.Add("上午 04:59");
            this.domainUpDown1.Items.Add("上午 05:00");
            this.domainUpDown1.Items.Add("上午 05:01");
            this.domainUpDown1.Items.Add("上午 05:02");
            this.domainUpDown1.Items.Add("上午 05:03");
            this.domainUpDown1.Items.Add("上午 05:04");
            this.domainUpDown1.Items.Add("上午 05:05");
            this.domainUpDown1.Items.Add("上午 05:06");
            this.domainUpDown1.Items.Add("上午 05:07");
            this.domainUpDown1.Items.Add("上午 05:08");
            this.domainUpDown1.Items.Add("上午 05:09");
            this.domainUpDown1.Items.Add("上午 05:10");
            this.domainUpDown1.Items.Add("上午 05:11");
            this.domainUpDown1.Items.Add("上午 05:12");
            this.domainUpDown1.Items.Add("上午 05:13");
            this.domainUpDown1.Items.Add("上午 05:14");
            this.domainUpDown1.Items.Add("上午 05:15");
            this.domainUpDown1.Items.Add("上午 05:16");
            this.domainUpDown1.Items.Add("上午 05:17");
            this.domainUpDown1.Items.Add("上午 05:18");
            this.domainUpDown1.Items.Add("上午 05:19");
            this.domainUpDown1.Items.Add("上午 05:20");
            this.domainUpDown1.Items.Add("上午 05:21");
            this.domainUpDown1.Items.Add("上午 05:22");
            this.domainUpDown1.Items.Add("上午 05:23");
            this.domainUpDown1.Items.Add("上午 05:24");
            this.domainUpDown1.Items.Add("上午 05:25");
            this.domainUpDown1.Items.Add("上午 05:26");
            this.domainUpDown1.Items.Add("上午 05:27");
            this.domainUpDown1.Items.Add("上午 05:28");
            this.domainUpDown1.Items.Add("上午 05:29");
            this.domainUpDown1.Items.Add("上午 05:30");
            this.domainUpDown1.Items.Add("上午 05:31");
            this.domainUpDown1.Items.Add("上午 05:32");
            this.domainUpDown1.Items.Add("上午 05:33");
            this.domainUpDown1.Items.Add("上午 05:34");
            this.domainUpDown1.Items.Add("上午 05:35");
            this.domainUpDown1.Items.Add("上午 05:36");
            this.domainUpDown1.Items.Add("上午 05:37");
            this.domainUpDown1.Items.Add("上午 05:38");
            this.domainUpDown1.Items.Add("上午 05:39");
            this.domainUpDown1.Items.Add("上午 05:40");
            this.domainUpDown1.Items.Add("上午 05:41");
            this.domainUpDown1.Items.Add("上午 05:42");
            this.domainUpDown1.Items.Add("上午 05:43");
            this.domainUpDown1.Items.Add("上午 05:44");
            this.domainUpDown1.Items.Add("上午 05:45");
            this.domainUpDown1.Items.Add("上午 05:46");
            this.domainUpDown1.Items.Add("上午 05:47");
            this.domainUpDown1.Items.Add("上午 05:48");
            this.domainUpDown1.Items.Add("上午 05:49");
            this.domainUpDown1.Items.Add("上午 05:50");
            this.domainUpDown1.Items.Add("上午 05:51");
            this.domainUpDown1.Items.Add("上午 05:52");
            this.domainUpDown1.Items.Add("上午 05:53");
            this.domainUpDown1.Items.Add("上午 05:54");
            this.domainUpDown1.Items.Add("上午 05:55");
            this.domainUpDown1.Items.Add("上午 05:56");
            this.domainUpDown1.Items.Add("上午 05:57");
            this.domainUpDown1.Items.Add("上午 05:58");
            this.domainUpDown1.Items.Add("上午 05:59");
            this.domainUpDown1.Items.Add("上午 06:00");
            this.domainUpDown1.Items.Add("上午 06:01");
            this.domainUpDown1.Items.Add("上午 06:02");
            this.domainUpDown1.Items.Add("上午 06:03");
            this.domainUpDown1.Items.Add("上午 06:04");
            this.domainUpDown1.Items.Add("上午 06:05");
            this.domainUpDown1.Items.Add("上午 06:06");
            this.domainUpDown1.Items.Add("上午 06:07");
            this.domainUpDown1.Items.Add("上午 06:08");
            this.domainUpDown1.Items.Add("上午 06:09");
            this.domainUpDown1.Items.Add("上午 06:10");
            this.domainUpDown1.Items.Add("上午 06:11");
            this.domainUpDown1.Items.Add("上午 06:12");
            this.domainUpDown1.Items.Add("上午 06:13");
            this.domainUpDown1.Items.Add("上午 06:14");
            this.domainUpDown1.Items.Add("上午 06:15");
            this.domainUpDown1.Items.Add("上午 06:16");
            this.domainUpDown1.Items.Add("上午 06:17");
            this.domainUpDown1.Items.Add("上午 06:18");
            this.domainUpDown1.Items.Add("上午 06:19");
            this.domainUpDown1.Items.Add("上午 06:20");
            this.domainUpDown1.Items.Add("上午 06:21");
            this.domainUpDown1.Items.Add("上午 06:22");
            this.domainUpDown1.Items.Add("上午 06:23");
            this.domainUpDown1.Items.Add("上午 06:24");
            this.domainUpDown1.Items.Add("上午 06:25");
            this.domainUpDown1.Items.Add("上午 06:26");
            this.domainUpDown1.Items.Add("上午 06:27");
            this.domainUpDown1.Items.Add("上午 06:28");
            this.domainUpDown1.Items.Add("上午 06:29");
            this.domainUpDown1.Items.Add("上午 06:30");
            this.domainUpDown1.Items.Add("上午 06:31");
            this.domainUpDown1.Items.Add("上午 06:32");
            this.domainUpDown1.Items.Add("上午 06:33");
            this.domainUpDown1.Items.Add("上午 06:34");
            this.domainUpDown1.Items.Add("上午 06:35");
            this.domainUpDown1.Items.Add("上午 06:36");
            this.domainUpDown1.Items.Add("上午 06:37");
            this.domainUpDown1.Items.Add("上午 06:38");
            this.domainUpDown1.Items.Add("上午 06:39");
            this.domainUpDown1.Items.Add("上午 06:40");
            this.domainUpDown1.Items.Add("上午 06:41");
            this.domainUpDown1.Items.Add("上午 06:42");
            this.domainUpDown1.Items.Add("上午 06:43");
            this.domainUpDown1.Items.Add("上午 06:44");
            this.domainUpDown1.Items.Add("上午 06:45");
            this.domainUpDown1.Items.Add("上午 06:46");
            this.domainUpDown1.Items.Add("上午 06:47");
            this.domainUpDown1.Items.Add("上午 06:48");
            this.domainUpDown1.Items.Add("上午 06:49");
            this.domainUpDown1.Items.Add("上午 06:50");
            this.domainUpDown1.Items.Add("上午 06:51");
            this.domainUpDown1.Items.Add("上午 06:52");
            this.domainUpDown1.Items.Add("上午 06:53");
            this.domainUpDown1.Items.Add("上午 06:54");
            this.domainUpDown1.Items.Add("上午 06:55");
            this.domainUpDown1.Items.Add("上午 06:56");
            this.domainUpDown1.Items.Add("上午 06:57");
            this.domainUpDown1.Items.Add("上午 06:58");
            this.domainUpDown1.Items.Add("上午 06:59");
            this.domainUpDown1.Items.Add("上午 07:00");
            this.domainUpDown1.Items.Add("上午 07:01");
            this.domainUpDown1.Items.Add("上午 07:02");
            this.domainUpDown1.Items.Add("上午 07:03");
            this.domainUpDown1.Items.Add("上午 07:04");
            this.domainUpDown1.Items.Add("上午 07:05");
            this.domainUpDown1.Items.Add("上午 07:06");
            this.domainUpDown1.Items.Add("上午 07:07");
            this.domainUpDown1.Items.Add("上午 07:08");
            this.domainUpDown1.Items.Add("上午 07:09");
            this.domainUpDown1.Items.Add("上午 07:10");
            this.domainUpDown1.Items.Add("上午 07:11");
            this.domainUpDown1.Items.Add("上午 07:12");
            this.domainUpDown1.Items.Add("上午 07:13");
            this.domainUpDown1.Items.Add("上午 07:14");
            this.domainUpDown1.Items.Add("上午 07:15");
            this.domainUpDown1.Items.Add("上午 07:16");
            this.domainUpDown1.Items.Add("上午 07:17");
            this.domainUpDown1.Items.Add("上午 07:18");
            this.domainUpDown1.Items.Add("上午 07:19");
            this.domainUpDown1.Items.Add("上午 07:20");
            this.domainUpDown1.Items.Add("上午 07:21");
            this.domainUpDown1.Items.Add("上午 07:22");
            this.domainUpDown1.Items.Add("上午 07:23");
            this.domainUpDown1.Items.Add("上午 07:24");
            this.domainUpDown1.Items.Add("上午 07:25");
            this.domainUpDown1.Items.Add("上午 07:26");
            this.domainUpDown1.Items.Add("上午 07:27");
            this.domainUpDown1.Items.Add("上午 07:28");
            this.domainUpDown1.Items.Add("上午 07:29");
            this.domainUpDown1.Items.Add("上午 07:30");
            this.domainUpDown1.Items.Add("上午 07:31");
            this.domainUpDown1.Items.Add("上午 07:32");
            this.domainUpDown1.Items.Add("上午 07:33");
            this.domainUpDown1.Items.Add("上午 07:34");
            this.domainUpDown1.Items.Add("上午 07:35");
            this.domainUpDown1.Items.Add("上午 07:36");
            this.domainUpDown1.Items.Add("上午 07:37");
            this.domainUpDown1.Items.Add("上午 07:38");
            this.domainUpDown1.Items.Add("上午 07:39");
            this.domainUpDown1.Items.Add("上午 07:40");
            this.domainUpDown1.Items.Add("上午 07:41");
            this.domainUpDown1.Items.Add("上午 07:42");
            this.domainUpDown1.Items.Add("上午 07:43");
            this.domainUpDown1.Items.Add("上午 07:44");
            this.domainUpDown1.Items.Add("上午 07:45");
            this.domainUpDown1.Items.Add("上午 07:46");
            this.domainUpDown1.Items.Add("上午 07:47");
            this.domainUpDown1.Items.Add("上午 07:48");
            this.domainUpDown1.Items.Add("上午 07:49");
            this.domainUpDown1.Items.Add("上午 07:50");
            this.domainUpDown1.Items.Add("上午 07:51");
            this.domainUpDown1.Items.Add("上午 07:52");
            this.domainUpDown1.Items.Add("上午 07:53");
            this.domainUpDown1.Items.Add("上午 07:54");
            this.domainUpDown1.Items.Add("上午 07:55");
            this.domainUpDown1.Items.Add("上午 07:56");
            this.domainUpDown1.Items.Add("上午 07:57");
            this.domainUpDown1.Items.Add("上午 07:58");
            this.domainUpDown1.Items.Add("上午 07:59");
            this.domainUpDown1.Items.Add("上午 08:00");
            this.domainUpDown1.Items.Add("上午 08:01");
            this.domainUpDown1.Items.Add("上午 08:02");
            this.domainUpDown1.Items.Add("上午 08:03");
            this.domainUpDown1.Items.Add("上午 08:04");
            this.domainUpDown1.Items.Add("上午 08:05");
            this.domainUpDown1.Items.Add("上午 08:06");
            this.domainUpDown1.Items.Add("上午 08:07");
            this.domainUpDown1.Items.Add("上午 08:08");
            this.domainUpDown1.Items.Add("上午 08:09");
            this.domainUpDown1.Items.Add("上午 08:10");
            this.domainUpDown1.Items.Add("上午 08:11");
            this.domainUpDown1.Items.Add("上午 08:12");
            this.domainUpDown1.Items.Add("上午 08:13");
            this.domainUpDown1.Items.Add("上午 08:14");
            this.domainUpDown1.Items.Add("上午 08:15");
            this.domainUpDown1.Items.Add("上午 08:16");
            this.domainUpDown1.Items.Add("上午 08:17");
            this.domainUpDown1.Items.Add("上午 08:18");
            this.domainUpDown1.Items.Add("上午 08:19");
            this.domainUpDown1.Items.Add("上午 08:20");
            this.domainUpDown1.Items.Add("上午 08:21");
            this.domainUpDown1.Items.Add("上午 08:22");
            this.domainUpDown1.Items.Add("上午 08:23");
            this.domainUpDown1.Items.Add("上午 08:24");
            this.domainUpDown1.Items.Add("上午 08:25");
            this.domainUpDown1.Items.Add("上午 08:26");
            this.domainUpDown1.Items.Add("上午 08:27");
            this.domainUpDown1.Items.Add("上午 08:28");
            this.domainUpDown1.Items.Add("上午 08:29");
            this.domainUpDown1.Items.Add("上午 08:30");
            this.domainUpDown1.Items.Add("上午 08:31");
            this.domainUpDown1.Items.Add("上午 08:32");
            this.domainUpDown1.Items.Add("上午 08:33");
            this.domainUpDown1.Items.Add("上午 08:34");
            this.domainUpDown1.Items.Add("上午 08:35");
            this.domainUpDown1.Items.Add("上午 08:36");
            this.domainUpDown1.Items.Add("上午 08:37");
            this.domainUpDown1.Items.Add("上午 08:38");
            this.domainUpDown1.Items.Add("上午 08:39");
            this.domainUpDown1.Items.Add("上午 08:40");
            this.domainUpDown1.Items.Add("上午 08:41");
            this.domainUpDown1.Items.Add("上午 08:42");
            this.domainUpDown1.Items.Add("上午 08:43");
            this.domainUpDown1.Items.Add("上午 08:44");
            this.domainUpDown1.Items.Add("上午 08:45");
            this.domainUpDown1.Items.Add("上午 08:46");
            this.domainUpDown1.Items.Add("上午 08:47");
            this.domainUpDown1.Items.Add("上午 08:48");
            this.domainUpDown1.Items.Add("上午 08:49");
            this.domainUpDown1.Items.Add("上午 08:50");
            this.domainUpDown1.Items.Add("上午 08:51");
            this.domainUpDown1.Items.Add("上午 08:52");
            this.domainUpDown1.Items.Add("上午 08:53");
            this.domainUpDown1.Items.Add("上午 08:54");
            this.domainUpDown1.Items.Add("上午 08:55");
            this.domainUpDown1.Items.Add("上午 08:56");
            this.domainUpDown1.Items.Add("上午 08:57");
            this.domainUpDown1.Items.Add("上午 08:58");
            this.domainUpDown1.Items.Add("上午 08:59");
            this.domainUpDown1.Items.Add("上午 09:00");
            this.domainUpDown1.Items.Add("上午 09:01");
            this.domainUpDown1.Items.Add("上午 09:02");
            this.domainUpDown1.Items.Add("上午 09:03");
            this.domainUpDown1.Items.Add("上午 09:04");
            this.domainUpDown1.Items.Add("上午 09:05");
            this.domainUpDown1.Items.Add("上午 09:06");
            this.domainUpDown1.Items.Add("上午 09:07");
            this.domainUpDown1.Items.Add("上午 09:08");
            this.domainUpDown1.Items.Add("上午 09:09");
            this.domainUpDown1.Items.Add("上午 09:10");
            this.domainUpDown1.Items.Add("上午 09:11");
            this.domainUpDown1.Items.Add("上午 09:12");
            this.domainUpDown1.Items.Add("上午 09:13");
            this.domainUpDown1.Items.Add("上午 09:14");
            this.domainUpDown1.Items.Add("上午 09:15");
            this.domainUpDown1.Items.Add("上午 09:16");
            this.domainUpDown1.Items.Add("上午 09:17");
            this.domainUpDown1.Items.Add("上午 09:18");
            this.domainUpDown1.Items.Add("上午 09:19");
            this.domainUpDown1.Items.Add("上午 09:20");
            this.domainUpDown1.Items.Add("上午 09:21");
            this.domainUpDown1.Items.Add("上午 09:22");
            this.domainUpDown1.Items.Add("上午 09:23");
            this.domainUpDown1.Items.Add("上午 09:24");
            this.domainUpDown1.Items.Add("上午 09:25");
            this.domainUpDown1.Items.Add("上午 09:26");
            this.domainUpDown1.Items.Add("上午 09:27");
            this.domainUpDown1.Items.Add("上午 09:28");
            this.domainUpDown1.Items.Add("上午 09:29");
            this.domainUpDown1.Items.Add("上午 09:30");
            this.domainUpDown1.Items.Add("上午 09:31");
            this.domainUpDown1.Items.Add("上午 09:32");
            this.domainUpDown1.Items.Add("上午 09:33");
            this.domainUpDown1.Items.Add("上午 09:34");
            this.domainUpDown1.Items.Add("上午 09:35");
            this.domainUpDown1.Items.Add("上午 09:36");
            this.domainUpDown1.Items.Add("上午 09:37");
            this.domainUpDown1.Items.Add("上午 09:38");
            this.domainUpDown1.Items.Add("上午 09:39");
            this.domainUpDown1.Items.Add("上午 09:40");
            this.domainUpDown1.Items.Add("上午 09:41");
            this.domainUpDown1.Items.Add("上午 09:42");
            this.domainUpDown1.Items.Add("上午 09:43");
            this.domainUpDown1.Items.Add("上午 09:44");
            this.domainUpDown1.Items.Add("上午 09:45");
            this.domainUpDown1.Items.Add("上午 09:46");
            this.domainUpDown1.Items.Add("上午 09:47");
            this.domainUpDown1.Items.Add("上午 09:48");
            this.domainUpDown1.Items.Add("上午 09:49");
            this.domainUpDown1.Items.Add("上午 09:50");
            this.domainUpDown1.Items.Add("上午 09:51");
            this.domainUpDown1.Items.Add("上午 09:52");
            this.domainUpDown1.Items.Add("上午 09:53");
            this.domainUpDown1.Items.Add("上午 09:54");
            this.domainUpDown1.Items.Add("上午 09:55");
            this.domainUpDown1.Items.Add("上午 09:56");
            this.domainUpDown1.Items.Add("上午 09:57");
            this.domainUpDown1.Items.Add("上午 09:58");
            this.domainUpDown1.Items.Add("上午 09:59");
            this.domainUpDown1.Items.Add("上午 10:00");
            this.domainUpDown1.Items.Add("上午 10:01");
            this.domainUpDown1.Items.Add("上午 10:02");
            this.domainUpDown1.Items.Add("上午 10:03");
            this.domainUpDown1.Items.Add("上午 10:04");
            this.domainUpDown1.Items.Add("上午 10:05");
            this.domainUpDown1.Items.Add("上午 10:06");
            this.domainUpDown1.Items.Add("上午 10:07");
            this.domainUpDown1.Items.Add("上午 10:08");
            this.domainUpDown1.Items.Add("上午 10:09");
            this.domainUpDown1.Items.Add("上午 10:10");
            this.domainUpDown1.Items.Add("上午 10:11");
            this.domainUpDown1.Items.Add("上午 10:12");
            this.domainUpDown1.Items.Add("上午 10:13");
            this.domainUpDown1.Items.Add("上午 10:14");
            this.domainUpDown1.Items.Add("上午 10:15");
            this.domainUpDown1.Items.Add("上午 10:16");
            this.domainUpDown1.Items.Add("上午 10:17");
            this.domainUpDown1.Items.Add("上午 10:18");
            this.domainUpDown1.Items.Add("上午 10:19");
            this.domainUpDown1.Items.Add("上午 10:20");
            this.domainUpDown1.Items.Add("上午 10:21");
            this.domainUpDown1.Items.Add("上午 10:22");
            this.domainUpDown1.Items.Add("上午 10:23");
            this.domainUpDown1.Items.Add("上午 10:24");
            this.domainUpDown1.Items.Add("上午 10:25");
            this.domainUpDown1.Items.Add("上午 10:26");
            this.domainUpDown1.Items.Add("上午 10:27");
            this.domainUpDown1.Items.Add("上午 10:28");
            this.domainUpDown1.Items.Add("上午 10:29");
            this.domainUpDown1.Items.Add("上午 10:30");
            this.domainUpDown1.Items.Add("上午 10:31");
            this.domainUpDown1.Items.Add("上午 10:32");
            this.domainUpDown1.Items.Add("上午 10:33");
            this.domainUpDown1.Items.Add("上午 10:34");
            this.domainUpDown1.Items.Add("上午 10:35");
            this.domainUpDown1.Items.Add("上午 10:36");
            this.domainUpDown1.Items.Add("上午 10:37");
            this.domainUpDown1.Items.Add("上午 10:38");
            this.domainUpDown1.Items.Add("上午 10:39");
            this.domainUpDown1.Items.Add("上午 10:40");
            this.domainUpDown1.Items.Add("上午 10:41");
            this.domainUpDown1.Items.Add("上午 10:42");
            this.domainUpDown1.Items.Add("上午 10:43");
            this.domainUpDown1.Items.Add("上午 10:44");
            this.domainUpDown1.Items.Add("上午 10:45");
            this.domainUpDown1.Items.Add("上午 10:46");
            this.domainUpDown1.Items.Add("上午 10:47");
            this.domainUpDown1.Items.Add("上午 10:48");
            this.domainUpDown1.Items.Add("上午 10:49");
            this.domainUpDown1.Items.Add("上午 10:50");
            this.domainUpDown1.Items.Add("上午 10:51");
            this.domainUpDown1.Items.Add("上午 10:52");
            this.domainUpDown1.Items.Add("上午 10:53");
            this.domainUpDown1.Items.Add("上午 10:54");
            this.domainUpDown1.Items.Add("上午 10:55");
            this.domainUpDown1.Items.Add("上午 10:56");
            this.domainUpDown1.Items.Add("上午 10:57");
            this.domainUpDown1.Items.Add("上午 10:58");
            this.domainUpDown1.Items.Add("上午 10:59");
            this.domainUpDown1.Items.Add("上午 11:00");
            this.domainUpDown1.Items.Add("上午 11:01");
            this.domainUpDown1.Items.Add("上午 11:02");
            this.domainUpDown1.Items.Add("上午 11:03");
            this.domainUpDown1.Items.Add("上午 11:04");
            this.domainUpDown1.Items.Add("上午 11:05");
            this.domainUpDown1.Items.Add("上午 11:06");
            this.domainUpDown1.Items.Add("上午 11:07");
            this.domainUpDown1.Items.Add("上午 11:08");
            this.domainUpDown1.Items.Add("上午 11:09");
            this.domainUpDown1.Items.Add("上午 11:10");
            this.domainUpDown1.Items.Add("上午 11:11");
            this.domainUpDown1.Items.Add("上午 11:12");
            this.domainUpDown1.Items.Add("上午 11:13");
            this.domainUpDown1.Items.Add("上午 11:14");
            this.domainUpDown1.Items.Add("上午 11:15");
            this.domainUpDown1.Items.Add("上午 11:16");
            this.domainUpDown1.Items.Add("上午 11:17");
            this.domainUpDown1.Items.Add("上午 11:18");
            this.domainUpDown1.Items.Add("上午 11:19");
            this.domainUpDown1.Items.Add("上午 11:20");
            this.domainUpDown1.Items.Add("上午 11:21");
            this.domainUpDown1.Items.Add("上午 11:22");
            this.domainUpDown1.Items.Add("上午 11:23");
            this.domainUpDown1.Items.Add("上午 11:24");
            this.domainUpDown1.Items.Add("上午 11:25");
            this.domainUpDown1.Items.Add("上午 11:26");
            this.domainUpDown1.Items.Add("上午 11:27");
            this.domainUpDown1.Items.Add("上午 11:28");
            this.domainUpDown1.Items.Add("上午 11:29");
            this.domainUpDown1.Items.Add("上午 11:30");
            this.domainUpDown1.Items.Add("上午 11:31");
            this.domainUpDown1.Items.Add("上午 11:32");
            this.domainUpDown1.Items.Add("上午 11:33");
            this.domainUpDown1.Items.Add("上午 11:34");
            this.domainUpDown1.Items.Add("上午 11:35");
            this.domainUpDown1.Items.Add("上午 11:36");
            this.domainUpDown1.Items.Add("上午 11:37");
            this.domainUpDown1.Items.Add("上午 11:38");
            this.domainUpDown1.Items.Add("上午 11:39");
            this.domainUpDown1.Items.Add("上午 11:40");
            this.domainUpDown1.Items.Add("上午 11:41");
            this.domainUpDown1.Items.Add("上午 11:42");
            this.domainUpDown1.Items.Add("上午 11:43");
            this.domainUpDown1.Items.Add("上午 11:44");
            this.domainUpDown1.Items.Add("上午 11:45");
            this.domainUpDown1.Items.Add("上午 11:46");
            this.domainUpDown1.Items.Add("上午 11:47");
            this.domainUpDown1.Items.Add("上午 11:48");
            this.domainUpDown1.Items.Add("上午 11:49");
            this.domainUpDown1.Items.Add("上午 11:50");
            this.domainUpDown1.Items.Add("上午 11:51");
            this.domainUpDown1.Items.Add("上午 11:52");
            this.domainUpDown1.Items.Add("上午 11:53");
            this.domainUpDown1.Items.Add("上午 11:54");
            this.domainUpDown1.Items.Add("上午 11:55");
            this.domainUpDown1.Items.Add("上午 11:56");
            this.domainUpDown1.Items.Add("上午 11:57");
            this.domainUpDown1.Items.Add("上午 11:58");
            this.domainUpDown1.Items.Add("上午 11:59");
            this.domainUpDown1.Items.Add("下午 12:00");
            this.domainUpDown1.Items.Add("下午 12:01");
            this.domainUpDown1.Items.Add("下午 12:02");
            this.domainUpDown1.Items.Add("下午 12:03");
            this.domainUpDown1.Items.Add("下午 12:04");
            this.domainUpDown1.Items.Add("下午 12:05");
            this.domainUpDown1.Items.Add("下午 12:06");
            this.domainUpDown1.Items.Add("下午 12:07");
            this.domainUpDown1.Items.Add("下午 12:08");
            this.domainUpDown1.Items.Add("下午 12:09");
            this.domainUpDown1.Items.Add("下午 12:10");
            this.domainUpDown1.Items.Add("下午 12:11");
            this.domainUpDown1.Items.Add("下午 12:12");
            this.domainUpDown1.Items.Add("下午 12:13");
            this.domainUpDown1.Items.Add("下午 12:14");
            this.domainUpDown1.Items.Add("下午 12:15");
            this.domainUpDown1.Items.Add("下午 12:16");
            this.domainUpDown1.Items.Add("下午 12:17");
            this.domainUpDown1.Items.Add("下午 12:18");
            this.domainUpDown1.Items.Add("下午 12:19");
            this.domainUpDown1.Items.Add("下午 12:20");
            this.domainUpDown1.Items.Add("下午 12:21");
            this.domainUpDown1.Items.Add("下午 12:22");
            this.domainUpDown1.Items.Add("下午 12:23");
            this.domainUpDown1.Items.Add("下午 12:24");
            this.domainUpDown1.Items.Add("下午 12:25");
            this.domainUpDown1.Items.Add("下午 12:26");
            this.domainUpDown1.Items.Add("下午 12:27");
            this.domainUpDown1.Items.Add("下午 12:28");
            this.domainUpDown1.Items.Add("下午 12:29");
            this.domainUpDown1.Items.Add("下午 12:30");
            this.domainUpDown1.Items.Add("下午 12:31");
            this.domainUpDown1.Items.Add("下午 12:32");
            this.domainUpDown1.Items.Add("下午 12:33");
            this.domainUpDown1.Items.Add("下午 12:34");
            this.domainUpDown1.Items.Add("下午 12:35");
            this.domainUpDown1.Items.Add("下午 12:36");
            this.domainUpDown1.Items.Add("下午 12:37");
            this.domainUpDown1.Items.Add("下午 12:38");
            this.domainUpDown1.Items.Add("下午 12:39");
            this.domainUpDown1.Items.Add("下午 12:40");
            this.domainUpDown1.Items.Add("下午 12:41");
            this.domainUpDown1.Items.Add("下午 12:42");
            this.domainUpDown1.Items.Add("下午 12:43");
            this.domainUpDown1.Items.Add("下午 12:44");
            this.domainUpDown1.Items.Add("下午 12:45");
            this.domainUpDown1.Items.Add("下午 12:46");
            this.domainUpDown1.Items.Add("下午 12:47");
            this.domainUpDown1.Items.Add("下午 12:48");
            this.domainUpDown1.Items.Add("下午 12:49");
            this.domainUpDown1.Items.Add("下午 12:50");
            this.domainUpDown1.Items.Add("下午 12:51");
            this.domainUpDown1.Items.Add("下午 12:52");
            this.domainUpDown1.Items.Add("下午 12:53");
            this.domainUpDown1.Items.Add("下午 12:54");
            this.domainUpDown1.Items.Add("下午 12:55");
            this.domainUpDown1.Items.Add("下午 12:56");
            this.domainUpDown1.Items.Add("下午 12:57");
            this.domainUpDown1.Items.Add("下午 12:58");
            this.domainUpDown1.Items.Add("下午 12:59");
            this.domainUpDown1.Items.Add("下午 01:00");
            this.domainUpDown1.Items.Add("下午 01:01");
            this.domainUpDown1.Items.Add("下午 01:02");
            this.domainUpDown1.Items.Add("下午 01:03");
            this.domainUpDown1.Items.Add("下午 01:04");
            this.domainUpDown1.Items.Add("下午 01:05");
            this.domainUpDown1.Items.Add("下午 01:06");
            this.domainUpDown1.Items.Add("下午 01:07");
            this.domainUpDown1.Items.Add("下午 01:08");
            this.domainUpDown1.Items.Add("下午 01:09");
            this.domainUpDown1.Items.Add("下午 01:10");
            this.domainUpDown1.Items.Add("下午 01:11");
            this.domainUpDown1.Items.Add("下午 01:12");
            this.domainUpDown1.Items.Add("下午 01:13");
            this.domainUpDown1.Items.Add("下午 01:14");
            this.domainUpDown1.Items.Add("下午 01:15");
            this.domainUpDown1.Items.Add("下午 01:16");
            this.domainUpDown1.Items.Add("下午 01:17");
            this.domainUpDown1.Items.Add("下午 01:18");
            this.domainUpDown1.Items.Add("下午 01:19");
            this.domainUpDown1.Items.Add("下午 01:20");
            this.domainUpDown1.Items.Add("下午 01:21");
            this.domainUpDown1.Items.Add("下午 01:22");
            this.domainUpDown1.Items.Add("下午 01:23");
            this.domainUpDown1.Items.Add("下午 01:24");
            this.domainUpDown1.Items.Add("下午 01:25");
            this.domainUpDown1.Items.Add("下午 01:26");
            this.domainUpDown1.Items.Add("下午 01:27");
            this.domainUpDown1.Items.Add("下午 01:28");
            this.domainUpDown1.Items.Add("下午 01:29");
            this.domainUpDown1.Items.Add("下午 01:30");
            this.domainUpDown1.Items.Add("下午 01:31");
            this.domainUpDown1.Items.Add("下午 01:32");
            this.domainUpDown1.Items.Add("下午 01:33");
            this.domainUpDown1.Items.Add("下午 01:34");
            this.domainUpDown1.Items.Add("下午 01:35");
            this.domainUpDown1.Items.Add("下午 01:36");
            this.domainUpDown1.Items.Add("下午 01:37");
            this.domainUpDown1.Items.Add("下午 01:38");
            this.domainUpDown1.Items.Add("下午 01:39");
            this.domainUpDown1.Items.Add("下午 01:40");
            this.domainUpDown1.Items.Add("下午 01:41");
            this.domainUpDown1.Items.Add("下午 01:42");
            this.domainUpDown1.Items.Add("下午 01:43");
            this.domainUpDown1.Items.Add("下午 01:44");
            this.domainUpDown1.Items.Add("下午 01:45");
            this.domainUpDown1.Items.Add("下午 01:46");
            this.domainUpDown1.Items.Add("下午 01:47");
            this.domainUpDown1.Items.Add("下午 01:48");
            this.domainUpDown1.Items.Add("下午 01:49");
            this.domainUpDown1.Items.Add("下午 01:50");
            this.domainUpDown1.Items.Add("下午 01:51");
            this.domainUpDown1.Items.Add("下午 01:52");
            this.domainUpDown1.Items.Add("下午 01:53");
            this.domainUpDown1.Items.Add("下午 01:54");
            this.domainUpDown1.Items.Add("下午 01:55");
            this.domainUpDown1.Items.Add("下午 01:56");
            this.domainUpDown1.Items.Add("下午 01:57");
            this.domainUpDown1.Items.Add("下午 01:58");
            this.domainUpDown1.Items.Add("下午 01:59");
            this.domainUpDown1.Items.Add("下午 02:00");
            this.domainUpDown1.Items.Add("下午 02:01");
            this.domainUpDown1.Items.Add("下午 02:02");
            this.domainUpDown1.Items.Add("下午 02:03");
            this.domainUpDown1.Items.Add("下午 02:04");
            this.domainUpDown1.Items.Add("下午 02:05");
            this.domainUpDown1.Items.Add("下午 02:06");
            this.domainUpDown1.Items.Add("下午 02:07");
            this.domainUpDown1.Items.Add("下午 02:08");
            this.domainUpDown1.Items.Add("下午 02:09");
            this.domainUpDown1.Items.Add("下午 02:10");
            this.domainUpDown1.Items.Add("下午 02:11");
            this.domainUpDown1.Items.Add("下午 02:12");
            this.domainUpDown1.Items.Add("下午 02:13");
            this.domainUpDown1.Items.Add("下午 02:14");
            this.domainUpDown1.Items.Add("下午 02:15");
            this.domainUpDown1.Items.Add("下午 02:16");
            this.domainUpDown1.Items.Add("下午 02:17");
            this.domainUpDown1.Items.Add("下午 02:18");
            this.domainUpDown1.Items.Add("下午 02:19");
            this.domainUpDown1.Items.Add("下午 02:20");
            this.domainUpDown1.Items.Add("下午 02:21");
            this.domainUpDown1.Items.Add("下午 02:22");
            this.domainUpDown1.Items.Add("下午 02:23");
            this.domainUpDown1.Items.Add("下午 02:24");
            this.domainUpDown1.Items.Add("下午 02:25");
            this.domainUpDown1.Items.Add("下午 02:26");
            this.domainUpDown1.Items.Add("下午 02:27");
            this.domainUpDown1.Items.Add("下午 02:28");
            this.domainUpDown1.Items.Add("下午 02:29");
            this.domainUpDown1.Items.Add("下午 02:30");
            this.domainUpDown1.Items.Add("下午 02:31");
            this.domainUpDown1.Items.Add("下午 02:32");
            this.domainUpDown1.Items.Add("下午 02:33");
            this.domainUpDown1.Items.Add("下午 02:34");
            this.domainUpDown1.Items.Add("下午 02:35");
            this.domainUpDown1.Items.Add("下午 02:36");
            this.domainUpDown1.Items.Add("下午 02:37");
            this.domainUpDown1.Items.Add("下午 02:38");
            this.domainUpDown1.Items.Add("下午 02:39");
            this.domainUpDown1.Items.Add("下午 02:40");
            this.domainUpDown1.Items.Add("下午 02:41");
            this.domainUpDown1.Items.Add("下午 02:42");
            this.domainUpDown1.Items.Add("下午 02:43");
            this.domainUpDown1.Items.Add("下午 02:44");
            this.domainUpDown1.Items.Add("下午 02:45");
            this.domainUpDown1.Items.Add("下午 02:46");
            this.domainUpDown1.Items.Add("下午 02:47");
            this.domainUpDown1.Items.Add("下午 02:48");
            this.domainUpDown1.Items.Add("下午 02:49");
            this.domainUpDown1.Items.Add("下午 02:50");
            this.domainUpDown1.Items.Add("下午 02:51");
            this.domainUpDown1.Items.Add("下午 02:52");
            this.domainUpDown1.Items.Add("下午 02:53");
            this.domainUpDown1.Items.Add("下午 02:54");
            this.domainUpDown1.Items.Add("下午 02:55");
            this.domainUpDown1.Items.Add("下午 02:56");
            this.domainUpDown1.Items.Add("下午 02:57");
            this.domainUpDown1.Items.Add("下午 02:58");
            this.domainUpDown1.Items.Add("下午 02:59");
            this.domainUpDown1.Items.Add("下午 03:00");
            this.domainUpDown1.Items.Add("下午 03:01");
            this.domainUpDown1.Items.Add("下午 03:02");
            this.domainUpDown1.Items.Add("下午 03:03");
            this.domainUpDown1.Items.Add("下午 03:04");
            this.domainUpDown1.Items.Add("下午 03:05");
            this.domainUpDown1.Items.Add("下午 03:06");
            this.domainUpDown1.Items.Add("下午 03:07");
            this.domainUpDown1.Items.Add("下午 03:08");
            this.domainUpDown1.Items.Add("下午 03:09");
            this.domainUpDown1.Items.Add("下午 03:10");
            this.domainUpDown1.Items.Add("下午 03:11");
            this.domainUpDown1.Items.Add("下午 03:12");
            this.domainUpDown1.Items.Add("下午 03:13");
            this.domainUpDown1.Items.Add("下午 03:14");
            this.domainUpDown1.Items.Add("下午 03:15");
            this.domainUpDown1.Items.Add("下午 03:16");
            this.domainUpDown1.Items.Add("下午 03:17");
            this.domainUpDown1.Items.Add("下午 03:18");
            this.domainUpDown1.Items.Add("下午 03:19");
            this.domainUpDown1.Items.Add("下午 03:20");
            this.domainUpDown1.Items.Add("下午 03:21");
            this.domainUpDown1.Items.Add("下午 03:22");
            this.domainUpDown1.Items.Add("下午 03:23");
            this.domainUpDown1.Items.Add("下午 03:24");
            this.domainUpDown1.Items.Add("下午 03:25");
            this.domainUpDown1.Items.Add("下午 03:26");
            this.domainUpDown1.Items.Add("下午 03:27");
            this.domainUpDown1.Items.Add("下午 03:28");
            this.domainUpDown1.Items.Add("下午 03:29");
            this.domainUpDown1.Items.Add("下午 03:30");
            this.domainUpDown1.Items.Add("下午 03:31");
            this.domainUpDown1.Items.Add("下午 03:32");
            this.domainUpDown1.Items.Add("下午 03:33");
            this.domainUpDown1.Items.Add("下午 03:34");
            this.domainUpDown1.Items.Add("下午 03:35");
            this.domainUpDown1.Items.Add("下午 03:36");
            this.domainUpDown1.Items.Add("下午 03:37");
            this.domainUpDown1.Items.Add("下午 03:38");
            this.domainUpDown1.Items.Add("下午 03:39");
            this.domainUpDown1.Items.Add("下午 03:40");
            this.domainUpDown1.Items.Add("下午 03:41");
            this.domainUpDown1.Items.Add("下午 03:42");
            this.domainUpDown1.Items.Add("下午 03:43");
            this.domainUpDown1.Items.Add("下午 03:44");
            this.domainUpDown1.Items.Add("下午 03:45");
            this.domainUpDown1.Items.Add("下午 03:46");
            this.domainUpDown1.Items.Add("下午 03:47");
            this.domainUpDown1.Items.Add("下午 03:48");
            this.domainUpDown1.Items.Add("下午 03:49");
            this.domainUpDown1.Items.Add("下午 03:50");
            this.domainUpDown1.Items.Add("下午 03:51");
            this.domainUpDown1.Items.Add("下午 03:52");
            this.domainUpDown1.Items.Add("下午 03:53");
            this.domainUpDown1.Items.Add("下午 03:54");
            this.domainUpDown1.Items.Add("下午 03:55");
            this.domainUpDown1.Items.Add("下午 03:56");
            this.domainUpDown1.Items.Add("下午 03:57");
            this.domainUpDown1.Items.Add("下午 03:58");
            this.domainUpDown1.Items.Add("下午 03:59");
            this.domainUpDown1.Items.Add("下午 04:00");
            this.domainUpDown1.Items.Add("下午 04:01");
            this.domainUpDown1.Items.Add("下午 04:02");
            this.domainUpDown1.Items.Add("下午 04:03");
            this.domainUpDown1.Items.Add("下午 04:04");
            this.domainUpDown1.Items.Add("下午 04:05");
            this.domainUpDown1.Items.Add("下午 04:06");
            this.domainUpDown1.Items.Add("下午 04:07");
            this.domainUpDown1.Items.Add("下午 04:08");
            this.domainUpDown1.Items.Add("下午 04:09");
            this.domainUpDown1.Items.Add("下午 04:10");
            this.domainUpDown1.Items.Add("下午 04:11");
            this.domainUpDown1.Items.Add("下午 04:12");
            this.domainUpDown1.Items.Add("下午 04:13");
            this.domainUpDown1.Items.Add("下午 04:14");
            this.domainUpDown1.Items.Add("下午 04:15");
            this.domainUpDown1.Items.Add("下午 04:16");
            this.domainUpDown1.Items.Add("下午 04:17");
            this.domainUpDown1.Items.Add("下午 04:18");
            this.domainUpDown1.Items.Add("下午 04:19");
            this.domainUpDown1.Items.Add("下午 04:20");
            this.domainUpDown1.Items.Add("下午 04:21");
            this.domainUpDown1.Items.Add("下午 04:22");
            this.domainUpDown1.Items.Add("下午 04:23");
            this.domainUpDown1.Items.Add("下午 04:24");
            this.domainUpDown1.Items.Add("下午 04:25");
            this.domainUpDown1.Items.Add("下午 04:26");
            this.domainUpDown1.Items.Add("下午 04:27");
            this.domainUpDown1.Items.Add("下午 04:28");
            this.domainUpDown1.Items.Add("下午 04:29");
            this.domainUpDown1.Items.Add("下午 04:30");
            this.domainUpDown1.Items.Add("下午 04:31");
            this.domainUpDown1.Items.Add("下午 04:32");
            this.domainUpDown1.Items.Add("下午 04:33");
            this.domainUpDown1.Items.Add("下午 04:34");
            this.domainUpDown1.Items.Add("下午 04:35");
            this.domainUpDown1.Items.Add("下午 04:36");
            this.domainUpDown1.Items.Add("下午 04:37");
            this.domainUpDown1.Items.Add("下午 04:38");
            this.domainUpDown1.Items.Add("下午 04:39");
            this.domainUpDown1.Items.Add("下午 04:40");
            this.domainUpDown1.Items.Add("下午 04:41");
            this.domainUpDown1.Items.Add("下午 04:42");
            this.domainUpDown1.Items.Add("下午 04:43");
            this.domainUpDown1.Items.Add("下午 04:44");
            this.domainUpDown1.Items.Add("下午 04:45");
            this.domainUpDown1.Items.Add("下午 04:46");
            this.domainUpDown1.Items.Add("下午 04:47");
            this.domainUpDown1.Items.Add("下午 04:48");
            this.domainUpDown1.Items.Add("下午 04:49");
            this.domainUpDown1.Items.Add("下午 04:50");
            this.domainUpDown1.Items.Add("下午 04:51");
            this.domainUpDown1.Items.Add("下午 04:52");
            this.domainUpDown1.Items.Add("下午 04:53");
            this.domainUpDown1.Items.Add("下午 04:54");
            this.domainUpDown1.Items.Add("下午 04:55");
            this.domainUpDown1.Items.Add("下午 04:56");
            this.domainUpDown1.Items.Add("下午 04:57");
            this.domainUpDown1.Items.Add("下午 04:58");
            this.domainUpDown1.Items.Add("下午 04:59");
            this.domainUpDown1.Items.Add("下午 05:00");
            this.domainUpDown1.Items.Add("下午 05:01");
            this.domainUpDown1.Items.Add("下午 05:02");
            this.domainUpDown1.Items.Add("下午 05:03");
            this.domainUpDown1.Items.Add("下午 05:04");
            this.domainUpDown1.Items.Add("下午 05:05");
            this.domainUpDown1.Items.Add("下午 05:06");
            this.domainUpDown1.Items.Add("下午 05:07");
            this.domainUpDown1.Items.Add("下午 05:08");
            this.domainUpDown1.Items.Add("下午 05:09");
            this.domainUpDown1.Items.Add("下午 05:10");
            this.domainUpDown1.Items.Add("下午 05:11");
            this.domainUpDown1.Items.Add("下午 05:12");
            this.domainUpDown1.Items.Add("下午 05:13");
            this.domainUpDown1.Items.Add("下午 05:14");
            this.domainUpDown1.Items.Add("下午 05:15");
            this.domainUpDown1.Items.Add("下午 05:16");
            this.domainUpDown1.Items.Add("下午 05:17");
            this.domainUpDown1.Items.Add("下午 05:18");
            this.domainUpDown1.Items.Add("下午 05:19");
            this.domainUpDown1.Items.Add("下午 05:20");
            this.domainUpDown1.Items.Add("下午 05:21");
            this.domainUpDown1.Items.Add("下午 05:22");
            this.domainUpDown1.Items.Add("下午 05:23");
            this.domainUpDown1.Items.Add("下午 05:24");
            this.domainUpDown1.Items.Add("下午 05:25");
            this.domainUpDown1.Items.Add("下午 05:26");
            this.domainUpDown1.Items.Add("下午 05:27");
            this.domainUpDown1.Items.Add("下午 05:28");
            this.domainUpDown1.Items.Add("下午 05:29");
            this.domainUpDown1.Items.Add("下午 05:30");
            this.domainUpDown1.Items.Add("下午 05:31");
            this.domainUpDown1.Items.Add("下午 05:32");
            this.domainUpDown1.Items.Add("下午 05:33");
            this.domainUpDown1.Items.Add("下午 05:34");
            this.domainUpDown1.Items.Add("下午 05:35");
            this.domainUpDown1.Items.Add("下午 05:36");
            this.domainUpDown1.Items.Add("下午 05:37");
            this.domainUpDown1.Items.Add("下午 05:38");
            this.domainUpDown1.Items.Add("下午 05:39");
            this.domainUpDown1.Items.Add("下午 05:40");
            this.domainUpDown1.Items.Add("下午 05:41");
            this.domainUpDown1.Items.Add("下午 05:42");
            this.domainUpDown1.Items.Add("下午 05:43");
            this.domainUpDown1.Items.Add("下午 05:44");
            this.domainUpDown1.Items.Add("下午 05:45");
            this.domainUpDown1.Items.Add("下午 05:46");
            this.domainUpDown1.Items.Add("下午 05:47");
            this.domainUpDown1.Items.Add("下午 05:48");
            this.domainUpDown1.Items.Add("下午 05:49");
            this.domainUpDown1.Items.Add("下午 05:50");
            this.domainUpDown1.Items.Add("下午 05:51");
            this.domainUpDown1.Items.Add("下午 05:52");
            this.domainUpDown1.Items.Add("下午 05:53");
            this.domainUpDown1.Items.Add("下午 05:54");
            this.domainUpDown1.Items.Add("下午 05:55");
            this.domainUpDown1.Items.Add("下午 05:56");
            this.domainUpDown1.Items.Add("下午 05:57");
            this.domainUpDown1.Items.Add("下午 05:58");
            this.domainUpDown1.Items.Add("下午 05:59");
            this.domainUpDown1.Items.Add("下午 06:00");
            this.domainUpDown1.Items.Add("下午 06:01");
            this.domainUpDown1.Items.Add("下午 06:02");
            this.domainUpDown1.Items.Add("下午 06:03");
            this.domainUpDown1.Items.Add("下午 06:04");
            this.domainUpDown1.Items.Add("下午 06:05");
            this.domainUpDown1.Items.Add("下午 06:06");
            this.domainUpDown1.Items.Add("下午 06:07");
            this.domainUpDown1.Items.Add("下午 06:08");
            this.domainUpDown1.Items.Add("下午 06:09");
            this.domainUpDown1.Items.Add("下午 06:10");
            this.domainUpDown1.Items.Add("下午 06:11");
            this.domainUpDown1.Items.Add("下午 06:12");
            this.domainUpDown1.Items.Add("下午 06:13");
            this.domainUpDown1.Items.Add("下午 06:14");
            this.domainUpDown1.Items.Add("下午 06:15");
            this.domainUpDown1.Items.Add("下午 06:16");
            this.domainUpDown1.Items.Add("下午 06:17");
            this.domainUpDown1.Items.Add("下午 06:18");
            this.domainUpDown1.Items.Add("下午 06:19");
            this.domainUpDown1.Items.Add("下午 06:20");
            this.domainUpDown1.Items.Add("下午 06:21");
            this.domainUpDown1.Items.Add("下午 06:22");
            this.domainUpDown1.Items.Add("下午 06:23");
            this.domainUpDown1.Items.Add("下午 06:24");
            this.domainUpDown1.Items.Add("下午 06:25");
            this.domainUpDown1.Items.Add("下午 06:26");
            this.domainUpDown1.Items.Add("下午 06:27");
            this.domainUpDown1.Items.Add("下午 06:28");
            this.domainUpDown1.Items.Add("下午 06:29");
            this.domainUpDown1.Items.Add("下午 06:30");
            this.domainUpDown1.Items.Add("下午 06:31");
            this.domainUpDown1.Items.Add("下午 06:32");
            this.domainUpDown1.Items.Add("下午 06:33");
            this.domainUpDown1.Items.Add("下午 06:34");
            this.domainUpDown1.Items.Add("下午 06:35");
            this.domainUpDown1.Items.Add("下午 06:36");
            this.domainUpDown1.Items.Add("下午 06:37");
            this.domainUpDown1.Items.Add("下午 06:38");
            this.domainUpDown1.Items.Add("下午 06:39");
            this.domainUpDown1.Items.Add("下午 06:40");
            this.domainUpDown1.Items.Add("下午 06:41");
            this.domainUpDown1.Items.Add("下午 06:42");
            this.domainUpDown1.Items.Add("下午 06:43");
            this.domainUpDown1.Items.Add("下午 06:44");
            this.domainUpDown1.Items.Add("下午 06:45");
            this.domainUpDown1.Items.Add("下午 06:46");
            this.domainUpDown1.Items.Add("下午 06:47");
            this.domainUpDown1.Items.Add("下午 06:48");
            this.domainUpDown1.Items.Add("下午 06:49");
            this.domainUpDown1.Items.Add("下午 06:50");
            this.domainUpDown1.Items.Add("下午 06:51");
            this.domainUpDown1.Items.Add("下午 06:52");
            this.domainUpDown1.Items.Add("下午 06:53");
            this.domainUpDown1.Items.Add("下午 06:54");
            this.domainUpDown1.Items.Add("下午 06:55");
            this.domainUpDown1.Items.Add("下午 06:56");
            this.domainUpDown1.Items.Add("下午 06:57");
            this.domainUpDown1.Items.Add("下午 06:58");
            this.domainUpDown1.Items.Add("下午 06:59");
            this.domainUpDown1.Items.Add("下午 07:00");
            this.domainUpDown1.Items.Add("下午 07:01");
            this.domainUpDown1.Items.Add("下午 07:02");
            this.domainUpDown1.Items.Add("下午 07:03");
            this.domainUpDown1.Items.Add("下午 07:04");
            this.domainUpDown1.Items.Add("下午 07:05");
            this.domainUpDown1.Items.Add("下午 07:06");
            this.domainUpDown1.Items.Add("下午 07:07");
            this.domainUpDown1.Items.Add("下午 07:08");
            this.domainUpDown1.Items.Add("下午 07:09");
            this.domainUpDown1.Items.Add("下午 07:10");
            this.domainUpDown1.Items.Add("下午 07:11");
            this.domainUpDown1.Items.Add("下午 07:12");
            this.domainUpDown1.Items.Add("下午 07:13");
            this.domainUpDown1.Items.Add("下午 07:14");
            this.domainUpDown1.Items.Add("下午 07:15");
            this.domainUpDown1.Items.Add("下午 07:16");
            this.domainUpDown1.Items.Add("下午 07:17");
            this.domainUpDown1.Items.Add("下午 07:18");
            this.domainUpDown1.Items.Add("下午 07:19");
            this.domainUpDown1.Items.Add("下午 07:20");
            this.domainUpDown1.Items.Add("下午 07:21");
            this.domainUpDown1.Items.Add("下午 07:22");
            this.domainUpDown1.Items.Add("下午 07:23");
            this.domainUpDown1.Items.Add("下午 07:24");
            this.domainUpDown1.Items.Add("下午 07:25");
            this.domainUpDown1.Items.Add("下午 07:26");
            this.domainUpDown1.Items.Add("下午 07:27");
            this.domainUpDown1.Items.Add("下午 07:28");
            this.domainUpDown1.Items.Add("下午 07:29");
            this.domainUpDown1.Items.Add("下午 07:30");
            this.domainUpDown1.Items.Add("下午 07:31");
            this.domainUpDown1.Items.Add("下午 07:32");
            this.domainUpDown1.Items.Add("下午 07:33");
            this.domainUpDown1.Items.Add("下午 07:34");
            this.domainUpDown1.Items.Add("下午 07:35");
            this.domainUpDown1.Items.Add("下午 07:36");
            this.domainUpDown1.Items.Add("下午 07:37");
            this.domainUpDown1.Items.Add("下午 07:38");
            this.domainUpDown1.Items.Add("下午 07:39");
            this.domainUpDown1.Items.Add("下午 07:40");
            this.domainUpDown1.Items.Add("下午 07:41");
            this.domainUpDown1.Items.Add("下午 07:42");
            this.domainUpDown1.Items.Add("下午 07:43");
            this.domainUpDown1.Items.Add("下午 07:44");
            this.domainUpDown1.Items.Add("下午 07:45");
            this.domainUpDown1.Items.Add("下午 07:46");
            this.domainUpDown1.Items.Add("下午 07:47");
            this.domainUpDown1.Items.Add("下午 07:48");
            this.domainUpDown1.Items.Add("下午 07:49");
            this.domainUpDown1.Items.Add("下午 07:50");
            this.domainUpDown1.Items.Add("下午 07:51");
            this.domainUpDown1.Items.Add("下午 07:52");
            this.domainUpDown1.Items.Add("下午 07:53");
            this.domainUpDown1.Items.Add("下午 07:54");
            this.domainUpDown1.Items.Add("下午 07:55");
            this.domainUpDown1.Items.Add("下午 07:56");
            this.domainUpDown1.Items.Add("下午 07:57");
            this.domainUpDown1.Items.Add("下午 07:58");
            this.domainUpDown1.Items.Add("下午 07:59");
            this.domainUpDown1.Items.Add("下午 08:00");
            this.domainUpDown1.Items.Add("下午 08:01");
            this.domainUpDown1.Items.Add("下午 08:02");
            this.domainUpDown1.Items.Add("下午 08:03");
            this.domainUpDown1.Items.Add("下午 08:04");
            this.domainUpDown1.Items.Add("下午 08:05");
            this.domainUpDown1.Items.Add("下午 08:06");
            this.domainUpDown1.Items.Add("下午 08:07");
            this.domainUpDown1.Items.Add("下午 08:08");
            this.domainUpDown1.Items.Add("下午 08:09");
            this.domainUpDown1.Items.Add("下午 08:10");
            this.domainUpDown1.Items.Add("下午 08:11");
            this.domainUpDown1.Items.Add("下午 08:12");
            this.domainUpDown1.Items.Add("下午 08:13");
            this.domainUpDown1.Items.Add("下午 08:14");
            this.domainUpDown1.Items.Add("下午 08:15");
            this.domainUpDown1.Items.Add("下午 08:16");
            this.domainUpDown1.Items.Add("下午 08:17");
            this.domainUpDown1.Items.Add("下午 08:18");
            this.domainUpDown1.Items.Add("下午 08:19");
            this.domainUpDown1.Items.Add("下午 08:20");
            this.domainUpDown1.Items.Add("下午 08:21");
            this.domainUpDown1.Items.Add("下午 08:22");
            this.domainUpDown1.Items.Add("下午 08:23");
            this.domainUpDown1.Items.Add("下午 08:24");
            this.domainUpDown1.Items.Add("下午 08:25");
            this.domainUpDown1.Items.Add("下午 08:26");
            this.domainUpDown1.Items.Add("下午 08:27");
            this.domainUpDown1.Items.Add("下午 08:28");
            this.domainUpDown1.Items.Add("下午 08:29");
            this.domainUpDown1.Items.Add("下午 08:30");
            this.domainUpDown1.Items.Add("下午 08:31");
            this.domainUpDown1.Items.Add("下午 08:32");
            this.domainUpDown1.Items.Add("下午 08:33");
            this.domainUpDown1.Items.Add("下午 08:34");
            this.domainUpDown1.Items.Add("下午 08:35");
            this.domainUpDown1.Items.Add("下午 08:36");
            this.domainUpDown1.Items.Add("下午 08:37");
            this.domainUpDown1.Items.Add("下午 08:38");
            this.domainUpDown1.Items.Add("下午 08:39");
            this.domainUpDown1.Items.Add("下午 08:40");
            this.domainUpDown1.Items.Add("下午 08:41");
            this.domainUpDown1.Items.Add("下午 08:42");
            this.domainUpDown1.Items.Add("下午 08:43");
            this.domainUpDown1.Items.Add("下午 08:44");
            this.domainUpDown1.Items.Add("下午 08:45");
            this.domainUpDown1.Items.Add("下午 08:46");
            this.domainUpDown1.Items.Add("下午 08:47");
            this.domainUpDown1.Items.Add("下午 08:48");
            this.domainUpDown1.Items.Add("下午 08:49");
            this.domainUpDown1.Items.Add("下午 08:50");
            this.domainUpDown1.Items.Add("下午 08:51");
            this.domainUpDown1.Items.Add("下午 08:52");
            this.domainUpDown1.Items.Add("下午 08:53");
            this.domainUpDown1.Items.Add("下午 08:54");
            this.domainUpDown1.Items.Add("下午 08:55");
            this.domainUpDown1.Items.Add("下午 08:56");
            this.domainUpDown1.Items.Add("下午 08:57");
            this.domainUpDown1.Items.Add("下午 08:58");
            this.domainUpDown1.Items.Add("下午 08:59");
            this.domainUpDown1.Items.Add("下午 09:00");
            this.domainUpDown1.Items.Add("下午 09:01");
            this.domainUpDown1.Items.Add("下午 09:02");
            this.domainUpDown1.Items.Add("下午 09:03");
            this.domainUpDown1.Items.Add("下午 09:04");
            this.domainUpDown1.Items.Add("下午 09:05");
            this.domainUpDown1.Items.Add("下午 09:06");
            this.domainUpDown1.Items.Add("下午 09:07");
            this.domainUpDown1.Items.Add("下午 09:08");
            this.domainUpDown1.Items.Add("下午 09:09");
            this.domainUpDown1.Items.Add("下午 09:10");
            this.domainUpDown1.Items.Add("下午 09:11");
            this.domainUpDown1.Items.Add("下午 09:12");
            this.domainUpDown1.Items.Add("下午 09:13");
            this.domainUpDown1.Items.Add("下午 09:14");
            this.domainUpDown1.Items.Add("下午 09:15");
            this.domainUpDown1.Items.Add("下午 09:16");
            this.domainUpDown1.Items.Add("下午 09:17");
            this.domainUpDown1.Items.Add("下午 09:18");
            this.domainUpDown1.Items.Add("下午 09:19");
            this.domainUpDown1.Items.Add("下午 09:20");
            this.domainUpDown1.Items.Add("下午 09:21");
            this.domainUpDown1.Items.Add("下午 09:22");
            this.domainUpDown1.Items.Add("下午 09:23");
            this.domainUpDown1.Items.Add("下午 09:24");
            this.domainUpDown1.Items.Add("下午 09:25");
            this.domainUpDown1.Items.Add("下午 09:26");
            this.domainUpDown1.Items.Add("下午 09:27");
            this.domainUpDown1.Items.Add("下午 09:28");
            this.domainUpDown1.Items.Add("下午 09:29");
            this.domainUpDown1.Items.Add("下午 09:30");
            this.domainUpDown1.Items.Add("下午 09:31");
            this.domainUpDown1.Items.Add("下午 09:32");
            this.domainUpDown1.Items.Add("下午 09:33");
            this.domainUpDown1.Items.Add("下午 09:34");
            this.domainUpDown1.Items.Add("下午 09:35");
            this.domainUpDown1.Items.Add("下午 09:36");
            this.domainUpDown1.Items.Add("下午 09:37");
            this.domainUpDown1.Items.Add("下午 09:38");
            this.domainUpDown1.Items.Add("下午 09:39");
            this.domainUpDown1.Items.Add("下午 09:40");
            this.domainUpDown1.Items.Add("下午 09:41");
            this.domainUpDown1.Items.Add("下午 09:42");
            this.domainUpDown1.Items.Add("下午 09:43");
            this.domainUpDown1.Items.Add("下午 09:44");
            this.domainUpDown1.Items.Add("下午 09:45");
            this.domainUpDown1.Items.Add("下午 09:46");
            this.domainUpDown1.Items.Add("下午 09:47");
            this.domainUpDown1.Items.Add("下午 09:48");
            this.domainUpDown1.Items.Add("下午 09:49");
            this.domainUpDown1.Items.Add("下午 09:50");
            this.domainUpDown1.Items.Add("下午 09:51");
            this.domainUpDown1.Items.Add("下午 09:52");
            this.domainUpDown1.Items.Add("下午 09:53");
            this.domainUpDown1.Items.Add("下午 09:54");
            this.domainUpDown1.Items.Add("下午 09:55");
            this.domainUpDown1.Items.Add("下午 09:56");
            this.domainUpDown1.Items.Add("下午 09:57");
            this.domainUpDown1.Items.Add("下午 09:58");
            this.domainUpDown1.Items.Add("下午 09:59");
            this.domainUpDown1.Items.Add("下午 10:00");
            this.domainUpDown1.Items.Add("下午 10:01");
            this.domainUpDown1.Items.Add("下午 10:02");
            this.domainUpDown1.Items.Add("下午 10:03");
            this.domainUpDown1.Items.Add("下午 10:04");
            this.domainUpDown1.Items.Add("下午 10:05");
            this.domainUpDown1.Items.Add("下午 10:06");
            this.domainUpDown1.Items.Add("下午 10:07");
            this.domainUpDown1.Items.Add("下午 10:08");
            this.domainUpDown1.Items.Add("下午 10:09");
            this.domainUpDown1.Items.Add("下午 10:10");
            this.domainUpDown1.Items.Add("下午 10:11");
            this.domainUpDown1.Items.Add("下午 10:12");
            this.domainUpDown1.Items.Add("下午 10:13");
            this.domainUpDown1.Items.Add("下午 10:14");
            this.domainUpDown1.Items.Add("下午 10:15");
            this.domainUpDown1.Items.Add("下午 10:16");
            this.domainUpDown1.Items.Add("下午 10:17");
            this.domainUpDown1.Items.Add("下午 10:18");
            this.domainUpDown1.Items.Add("下午 10:19");
            this.domainUpDown1.Items.Add("下午 10:20");
            this.domainUpDown1.Items.Add("下午 10:21");
            this.domainUpDown1.Items.Add("下午 10:22");
            this.domainUpDown1.Items.Add("下午 10:23");
            this.domainUpDown1.Items.Add("下午 10:24");
            this.domainUpDown1.Items.Add("下午 10:25");
            this.domainUpDown1.Items.Add("下午 10:26");
            this.domainUpDown1.Items.Add("下午 10:27");
            this.domainUpDown1.Items.Add("下午 10:28");
            this.domainUpDown1.Items.Add("下午 10:29");
            this.domainUpDown1.Items.Add("下午 10:30");
            this.domainUpDown1.Items.Add("下午 10:31");
            this.domainUpDown1.Items.Add("下午 10:32");
            this.domainUpDown1.Items.Add("下午 10:33");
            this.domainUpDown1.Items.Add("下午 10:34");
            this.domainUpDown1.Items.Add("下午 10:35");
            this.domainUpDown1.Items.Add("下午 10:36");
            this.domainUpDown1.Items.Add("下午 10:37");
            this.domainUpDown1.Items.Add("下午 10:38");
            this.domainUpDown1.Items.Add("下午 10:39");
            this.domainUpDown1.Items.Add("下午 10:40");
            this.domainUpDown1.Items.Add("下午 10:41");
            this.domainUpDown1.Items.Add("下午 10:42");
            this.domainUpDown1.Items.Add("下午 10:43");
            this.domainUpDown1.Items.Add("下午 10:44");
            this.domainUpDown1.Items.Add("下午 10:45");
            this.domainUpDown1.Items.Add("下午 10:46");
            this.domainUpDown1.Items.Add("下午 10:47");
            this.domainUpDown1.Items.Add("下午 10:48");
            this.domainUpDown1.Items.Add("下午 10:49");
            this.domainUpDown1.Items.Add("下午 10:50");
            this.domainUpDown1.Items.Add("下午 10:51");
            this.domainUpDown1.Items.Add("下午 10:52");
            this.domainUpDown1.Items.Add("下午 10:53");
            this.domainUpDown1.Items.Add("下午 10:54");
            this.domainUpDown1.Items.Add("下午 10:55");
            this.domainUpDown1.Items.Add("下午 10:56");
            this.domainUpDown1.Items.Add("下午 10:57");
            this.domainUpDown1.Items.Add("下午 10:58");
            this.domainUpDown1.Items.Add("下午 10:59");
            this.domainUpDown1.Items.Add("下午 11:00");
            this.domainUpDown1.Items.Add("下午 11:01");
            this.domainUpDown1.Items.Add("下午 11:02");
            this.domainUpDown1.Items.Add("下午 11:03");
            this.domainUpDown1.Items.Add("下午 11:04");
            this.domainUpDown1.Items.Add("下午 11:05");
            this.domainUpDown1.Items.Add("下午 11:06");
            this.domainUpDown1.Items.Add("下午 11:07");
            this.domainUpDown1.Items.Add("下午 11:08");
            this.domainUpDown1.Items.Add("下午 11:09");
            this.domainUpDown1.Items.Add("下午 11:10");
            this.domainUpDown1.Items.Add("下午 11:11");
            this.domainUpDown1.Items.Add("下午 11:12");
            this.domainUpDown1.Items.Add("下午 11:13");
            this.domainUpDown1.Items.Add("下午 11:14");
            this.domainUpDown1.Items.Add("下午 11:15");
            this.domainUpDown1.Items.Add("下午 11:16");
            this.domainUpDown1.Items.Add("下午 11:17");
            this.domainUpDown1.Items.Add("下午 11:18");
            this.domainUpDown1.Items.Add("下午 11:19");
            this.domainUpDown1.Items.Add("下午 11:20");
            this.domainUpDown1.Items.Add("下午 11:21");
            this.domainUpDown1.Items.Add("下午 11:22");
            this.domainUpDown1.Items.Add("下午 11:23");
            this.domainUpDown1.Items.Add("下午 11:24");
            this.domainUpDown1.Items.Add("下午 11:25");
            this.domainUpDown1.Items.Add("下午 11:26");
            this.domainUpDown1.Items.Add("下午 11:27");
            this.domainUpDown1.Items.Add("下午 11:28");
            this.domainUpDown1.Items.Add("下午 11:29");
            this.domainUpDown1.Items.Add("下午 11:30");
            this.domainUpDown1.Items.Add("下午 11:31");
            this.domainUpDown1.Items.Add("下午 11:32");
            this.domainUpDown1.Items.Add("下午 11:33");
            this.domainUpDown1.Items.Add("下午 11:34");
            this.domainUpDown1.Items.Add("下午 11:35");
            this.domainUpDown1.Items.Add("下午 11:36");
            this.domainUpDown1.Items.Add("下午 11:37");
            this.domainUpDown1.Items.Add("下午 11:38");
            this.domainUpDown1.Items.Add("下午 11:39");
            this.domainUpDown1.Items.Add("下午 11:40");
            this.domainUpDown1.Items.Add("下午 11:41");
            this.domainUpDown1.Items.Add("下午 11:42");
            this.domainUpDown1.Items.Add("下午 11:43");
            this.domainUpDown1.Items.Add("下午 11:44");
            this.domainUpDown1.Items.Add("下午 11:45");
            this.domainUpDown1.Items.Add("下午 11:46");
            this.domainUpDown1.Items.Add("下午 11:47");
            this.domainUpDown1.Items.Add("下午 11:48");
            this.domainUpDown1.Items.Add("下午 11:49");
            this.domainUpDown1.Items.Add("下午 11:50");
            this.domainUpDown1.Items.Add("下午 11:51");
            this.domainUpDown1.Items.Add("下午 11:52");
            this.domainUpDown1.Items.Add("下午 11:53");
            this.domainUpDown1.Items.Add("下午 11:54");
            this.domainUpDown1.Items.Add("下午 11:55");
            this.domainUpDown1.Items.Add("下午 11:56");
            this.domainUpDown1.Items.Add("下午 11:57");
            this.domainUpDown1.Items.Add("下午 11:58");
            this.domainUpDown1.Items.Add("下午 11:59");
            this.domainUpDown1.Location = new System.Drawing.Point(676, 192);
            this.domainUpDown1.Name = "domainUpDown1";
            this.domainUpDown1.Size = new System.Drawing.Size(108, 22);
            this.domainUpDown1.TabIndex = 5;
            this.domainUpDown1.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.domainUpDown1.Wrap = true;
            // 
            // textBox1
            // 
            this.textBox1.Location = new System.Drawing.Point(918, 12);
            this.textBox1.Multiline = true;
            this.textBox1.Name = "textBox1";
            this.textBox1.ReadOnly = true;
            this.textBox1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.textBox1.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.textBox1.Size = new System.Drawing.Size(243, 189);
            this.textBox1.TabIndex = 6;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("新細明體", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(136)));
            this.label3.Location = new System.Drawing.Point(810, 155);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(41, 15);
            this.label3.TabIndex = 7;
            this.label3.Text = "label3";
            // 
            // button3
            // 
            this.button3.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.button3.Location = new System.Drawing.Point(918, 207);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(75, 23);
            this.button3.TabIndex = 8;
            this.button3.Text = "匯出記錄檔";
            this.button3.UseVisualStyleBackColor = true;
            this.button3.Click += new System.EventHandler(this.button3_Click);
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(285, 66);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(17, 12);
            this.label4.TabIndex = 9;
            this.label4.Text = "●";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(285, 123);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(17, 12);
            this.label5.TabIndex = 10;
            this.label5.Text = "●";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(545, 66);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(17, 12);
            this.label6.TabIndex = 11;
            this.label6.Text = "●";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(545, 123);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(17, 12);
            this.label7.TabIndex = 12;
            this.label7.Text = "●";
            // 
            // timer1
            // 
            this.timer1.Enabled = true;
            this.timer1.Tick += new System.EventHandler(this.timer1_Tick);
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1170, 241);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.button3);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.textBox1);
            this.Controls.Add(this.domainUpDown1);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.button1);
            this.Name = "Form1";
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.Form1_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Button button2;
        private System.Windows.Forms.DomainUpDown domainUpDown1;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Button button3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Timer timer1;
    }
}

